server {
    listen 1024;
    location / {
    }

    location /submit/ {
        methods POST;
        client_max_body_size 2;
        index name.txt;
    }
}

server {
    listen 1025;
    location /white/ {
        index index_white.html;
    }
}

server {
    listen 1026;
    root www/green;
    index index_green.html;
    location / {
    }
}
