server {
    listen 1024;

    location / {
    }

    location /name {
        index name.html;
    }
}

server {
    listen 1025;

    root www/white;
    location / {
        index index.html;
    }
}
