#!/usr/bin/python3
import sys

body = """<html>
<head><title>Webserv CGI Test</title></head>
<body>
    <h1>CGI Power!</h1>
    <p>This output was generated by a Python script.</p>
    <p>If you see this, your pipes and execve are working.</p>
</body>
</html>"""

# Header
sys.stdout.write("Content-Type: text/html\r\n")
sys.stdout.write(f"Content-Length: {len(body.encode('utf-8'))}\r\n")
sys.stdout.write("\r\n") # The delimiter

# Body
sys.stdout.write(body)
