#!/usr/bin/python3
import sys

# Define the body first to calculate length
body = """<html>
<head><title>Webserv CGI Test</title></head>
<body>
    <h1>CGI Power!</h1>
    <p>This output was generated by a Python script.</p>
    <p>If you see this, your pipes and execve are working.</p>
</body>
</html>"""

sys.stdout.write(body)
