#!/bin/bash

# Define the body
body="<html>
<head><title>Webserv CGI Bash Test</title></head>
<body>
    <h1>CGI Power from Bash!</h1>
    <p>This output was generated by a Shell script.</p>
    <p><b>Method:</b> $REQUEST_METHOD</p>
</body>
</html>"

# Output body
echo "$body"
