package main

import (
	"fmt"
)

func main() {
	// In a real CGI scenario, you might want to print headers first
	// e.g., fmt.Print("Content-Type: text/html\r\n\r\n")

	body := `<html>
<head><title>Webserv CGI Test</title></head>
<body>
    <h1>CGI Power!</h1>
    <p>This output was generated by a Go binary.</p>
    <p>If you see this, your pipes and execve are working.</p>
</body>
</html>`

	fmt.Print(body)
}
