#!/usr/bin/perl

# CGI requires headers first
print "Content-Type: text/html\r\n";
print "Status: 200 OK\r\n\r\n";

my $body = <<'END_HTML';
<html>
<head><title>Webserv CGI Perl Test</title></head>
<body>
    <h1>CGI Power from Perl!</h1>
    <p>This output was generated by a Perl script.</p>
    <p>The "Grandfather" of CGI is still alive!</p>
</body>
</html>
END_HTML

print $body;
