#!/usr/bin/ruby

# Define the body
body = <<~HTML
  <html>
  <head><title>Webserv CGI Ruby Test</title></head>
  <body>
      <h1>CGI Power from Ruby!</h1>
      <p>This output was generated by a Ruby script.</p>
      <p>Clean, elegant, and working.</p>
  </body>
  </html>
HTML

# Output headers
puts "Content-Type: text/html\r\n"
puts "Content-Length: #{body.bytesize}\r\n"
puts "\r\n"

# Output body
print body
