#!/usr/bin/python3
import sys

# Define the body first to calculate length
body = """<html>
<head><title>Webserv CGI Test</title></head>
<body>
    <h1>CGI Power!</h1>
    <p>This output was generated by a Python script.</p>
    <p>If you see this, your pipes and execve are working.</p>
</body>
</html>"""

# 1. Status Line
print("HTTP/1.1 200 OK")

# 2. Headers
print("Server: webserv")
print("Content-Type: text/html")
print(f"Content-Length: {len(body)}")

# 3. The mandatory empty line that separates headers from body
print("")

# 4. The actual content
sys.stdout.write(body)
