#!/bin/bash

body="<html>
<head><title>Webserv CGI Bash Test</title></head>
<body>
    <h1>CGI Power from Bash!</h1>
    <p>This output was generated by a Shell script.</p>
</body>
</html>"

# Output headers
echo -e "Content-Type: text/html"
echo -e "Content-Length: ${#body}"
echo -e "\r\n" # The delimiter

# Output body
echo "$body"
