name: Webserv CI/CD

# Trigger workflow
on:
  push:
  pull_request:
    branches: ["main"]

jobs:

# |--- 1. UNIT TESTS ----------------------------------------------------------|

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Unit Tests
        run: |
          cd tests
          make unit

      - name: Run Unit Tests
        run: |
          cd tests
          ./unit_test

# |--- 2. INTEGRATION TESTS ---------------------------------------------------|

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Integration Tests
        run: |
          cd tests
          make integration

      - name: Run Integration Tests
        run: |
          cd tests
          ./integ_test

# |--- 3. E2E TESTS -----------------------------------------------------------|

  e2e-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Test Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y valgrind siege python3-pip
          pip3 install -r tests/src/e2e_test/requirements.txt

      - name: Compile Webserv
        run: make

      - name: Run E2E Python Tests
        run: |
          # start server
          ./webserv tests/conf-files/test25.conf & SERVER_PID=$!

          # setup-time
          sleep 2

          # E2E-test
          pytest tests/src/e2e_test/e2e_test.py -v

          # shut-down server
          kill -SIGTERM $SERVER_PID || true
          wait $SERVER_PID || true

      - name: Run Siege Test with Valgrind
        run: |
          # start server using valgrind
          valgrind --leak-check=full --error-exitcode=1 ./webserv tests/conf-files/test25.conf & SERVER_PID=$!

          # setup-time
          sleep 2

          # siege-test
          siege -c5 -r3 http://127.0.0.1:1024/

          # shut-down server
          kill -SIGTERM $SERVER_PID || true
          wait $SERVER_PID || true
